// Generated by tooling/schema-compiler/compile_schema.py. Do not edit.
package dev.tracebox.directboot

import dev.tracebox.api.generated.GeneratedEmergencyRecord

/** Fingerprint of only the canonical Direct Boot-eligible projection and its policy category. */
object GeneratedDirectBootSchemaFingerprint {
    const val HEX: String = "5e03bee44c26103d4914c9c143b0c750343e161f989754c8bcb70d25b5903ab6"

    fun bytes(): ByteArray = ByteArray(HEX.length / 2) { index ->
        HEX.substring(index * 2, index * 2 + 2).toInt(16).toByte()
    }
}

/** Generated C0-only Direct Boot projection. No arbitrary payload or privacy override exists. */
internal data class C0DirectBootRecord(
    val schemaFingerprint: ByteArray,
    val slotSequence: ULong,
    val policyEpoch: ULong,
    val signalNumber: Int,
    val signalCode: Int,
    val processRole: UInt,
    val threadRole: UInt,
    val flags: ULong,
    val elapsedMillis: Long,
    val readinessCode: Int,
    val categoryMask: Long,
) {
    init {
        require(schemaFingerprint.size == 32)
        require(policyEpoch <= Long.MAX_VALUE.toULong())
        require(elapsedMillis >= 0)
        require(readinessCode in 0..255)
        require(categoryMask in GENERATED_DIRECT_BOOT_CATEGORIES)
    }
}

/** Schema-generated wrapper admitting only events whose complete schema is C0. */
class GeneratedDirectBootRecord private constructor(
    internal val c0: C0DirectBootRecord,
) {
    companion object {
        fun fromEmergency(
            schemaFingerprint: ByteArray,
            value: GeneratedEmergencyRecord,
            elapsedMillis: Long,
            readinessCode: Int,
        ): GeneratedDirectBootRecord {
            return GeneratedDirectBootRecord(
                C0DirectBootRecord(
                    schemaFingerprint.copyOf(),
                    value.slot_sequence,
                    value.policy_epoch,
                    value.signal_number,
                    value.signal_code,
                    value.process_role,
                    value.thread_role,
                    value.flags,
                    elapsedMillis,
                    readinessCode,
                    2L,
                ),
            )
        }

        @Deprecated(
            message = "The category is generated and cannot be overridden",
            replaceWith = ReplaceWith("fromEmergency(schemaFingerprint, value, elapsedMillis, readinessCode)"),
        )
        fun fromEmergency(
            schemaFingerprint: ByteArray,
            value: GeneratedEmergencyRecord,
            elapsedMillis: Long,
            readinessCode: Int,
            categoryMask: Long,
        ): GeneratedDirectBootRecord {
            require(categoryMask == 2L)
            return fromEmergency(schemaFingerprint, value, elapsedMillis, readinessCode)
        }

    }
}

internal val GENERATED_DIRECT_BOOT_CATEGORIES = setOf(
    2L,
)
