[workspace]
members = [
    "rust/tbdiag-phase0",
    "rust/tbdiag-format",
    "rust/tbdiag-cli",
    "rust/tracebox-phase0",
    "rust/tracebox-sys",
    "rust/tracebox",
    "rust/tracebox-identity",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "Apache-2.0"
rust-version = "1.93.1"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "deny"
pedantic = "deny"

[profile.release]
panic = "abort"