/* Generated by tooling/schema-compiler/compile_schema.py. Do not edit. */
#ifndef TRACEBOX_GENERATED_EVENTS_H_
#define TRACEBOX_GENERATED_EVENTS_H_
#include <stdint.h>
typedef enum {
  TB_EVENT_STRUCTURALSUMMARY = 1,
  TB_EVENT_EMERGENCYRECORD = 2,
  TB_EVENT_BREADCRUMB = 3,
  TB_EVENT_HANDLEDERROR = 4,
} tb_event_id_v1;
typedef enum { TB_PROCESS_ROLE_APP = 1, TB_THREAD_ROLE_UNKNOWN = 0 } tb_generated_role_v1;
#endif
