"""Generate all Phase 1 schema consumers from one strict JSON model."""
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tooling" / "schema-model"))
from schema_model import SchemaError, parse_schema  # noqa: E402


def _kotlin_name(name: str) -> str:
    return name[:1].lower() + name[1:]


def render(schema, fingerprint: str) -> dict[str, str]:
    kotlin_types = {"u16": "UShort", "u32": "UInt", "u64": "ULong", "i32": "Int", "enum": "UInt", "fixed32": "UInt"}
    c_types = {"u16": "uint16_t", "u32": "uint32_t", "u64": "uint64_t", "i32": "int32_t", "enum": "uint32_t", "fixed32": "uint32_t"}
    rust_types = {"u16": "u16", "u32": "u32", "u64": "u64", "i32": "i32", "enum": "u32", "fixed32": "u32"}
    protobuf_types = {"u16": "uint32", "u32": "uint32", "u64": "uint64", "i32": "int32", "enum": "uint32", "fixed32": "fixed32"}
    metadata = {
        "schema_version": schema.version,
        "fingerprint": fingerprint,
        "events": [
            {
                "id": event.id, "name": event.name, "category": event.category,
                "retention": event.retention, "package_visibility": event.package_visibility,
                "direct_boot_eligible": event.direct_boot_eligible,
                "fields": [field.__dict__ for field in event.fields],
            } for event in schema.events
        ],
    }
    kotlin = """// Generated by tooling/schema-compiler/compile_schema.py. Do not edit.
package dev.tracebox.api.generated

import dev.tracebox.api.DiagnosticContext
import dev.tracebox.api.Diagnostics

enum class GeneratedEventId(val stableId: Int) {
""" + "".join(f"    {event.name.upper()}({event.id}),\n" for event in schema.events) + "}\n\n"
    kotlin += """/** A schema-defined, bounded recording value. */
sealed interface GeneratedRecord {
    val eventId: GeneratedEventId
}

"""
    for event in schema.events:
        params = "\n".join(f"    val {_kotlin_name(field.name)}: {kotlin_types[field.semantic_type]}," for field in event.fields)
        kotlin += f"""/** Schema event {event.id}; fields are privacy-classified in the schema. */
class Generated{event.name} internal constructor(
{params}
) : GeneratedRecord {{
    override val eventId = GeneratedEventId.{event.name.upper()}
}}

"""
    kotlin += "object GeneratedDiagnostics {\n"
    for event in schema.events:
        params = ", ".join(f"{_kotlin_name(field.name)}: {kotlin_types[field.semantic_type]}" for field in event.fields)
        args = ", ".join(_kotlin_name(field.name) for field in event.fields)
        kotlin += f"""    fun {_kotlin_name(event.name)}(diagnostics: Diagnostics, {params}, context: DiagnosticContext? = null) {{
        if (diagnostics.eventEnabled(GeneratedEventId.{event.name.upper()})) {{
            diagnostics.record(Generated{event.name}({args}), context)
        }}
    }}
"""
    kotlin += "}\n"
    c = """/* Generated by tooling/schema-compiler/compile_schema.py. Do not edit. */
#ifndef TRACEBOX_GENERATED_EVENTS_H_
#define TRACEBOX_GENERATED_EVENTS_H_
#include <stdint.h>
/* Requires tb_header_v1 and tb_status_v1 from tracebox/abi.h, which are
 * defined before this header is included there. Do not include this
 * header directly; include tracebox/abi.h instead. */
#ifdef __cplusplus
extern "C" {
#endif
typedef enum {
""" + "".join(f"  TB_EVENT_{event.name.upper()} = {event.id},\n" for event in schema.events) + "} tb_event_id_v1;\n\n"
    for event in schema.events:
        c += f"typedef struct {{\n  tb_header_v1 header;\n"
        c += "".join(f"  {c_types[field.semantic_type]} {field.name}; /* {field.privacy}, max encoded {field.max_encoded_size} */\n" for field in event.fields)
        c += f"}} tb_generated_{event.name.lower()}_v1;\n"
        c += f"tb_status_v1 tb_record_generated_{event.name.lower()}_v1(const tb_generated_{event.name.lower()}_v1* value, uint32_t recorder_ready);\n\n"
    c += "#ifdef __cplusplus\n}\n#endif\n\n#endif\n"
    rust = (
        "// Generated by tooling/schema-compiler/compile_schema.py. Do not edit.\n"
        + "pub const SCHEMA_FINGERPRINT: &str = \"" + fingerprint + "\";\n"
        + "#[repr(u32)]\n#[derive(Clone, Copy, Debug, PartialEq, Eq)]\npub enum EventId {\n"
        + "".join(f"    {event.name} = {event.id},\n" for event in schema.events)
        + "}\n\n"
    )
    for event in schema.events:
        rust += f"/// Schema-defined C ABI input for event {event.id}.\n#[repr(C)]\n#[derive(Clone, Copy, Debug, PartialEq, Eq)]\npub struct {event.name}V1 {{\n    /// Required ABI header.\n    pub header: crate::HeaderV1,\n"
        rust += "".join(f"    /// {field.privacy}; maximum encoded size {field.max_encoded_size}.\n    pub {field.name}: {rust_types[field.semantic_type]},\n" for field in event.fields)
        rust += "}\n\n"
    rust = rust.rstrip() + "\n"
    proto = "// Generated protobuf-compatible definitions. No free-form values.\nsyntax = \"proto3\";\npackage tracebox.generated;\n" + "".join(
        "message " + event.name + " {\n" + "".join(
            f"  {protobuf_types[field.semantic_type]} {field.name} = {field.id}; // max encoded size {field.max_encoded_size}; privacy {field.privacy}\n" for field in event.fields
        ) + "}\n" for event in schema.events
    )
    labels = {
        event.name: f"{event.category}: includes only " +
        ", ".join(f"{field.privacy} {field.name}" for field in event.fields)
        for event in schema.events
    }
    docs = "# Generated Tracebox schema reference\n\n"
    for event in schema.events:
        docs += f"## {event.name} (`{event.id}`)\n\n"
        docs += f"Category: `{event.category}`; retention: `{event.retention}`; package: `{event.package_visibility}`; Direct Boot: `{event.direct_boot_eligible}`.\n\n"
        docs += "| Field ID | Field | Privacy | Type | Maximum encoded size | Transformation |\n|---:|---|---|---|---:|---|\n"
        docs += "".join(f"| {field.id} | {field.name} | {field.privacy} | {field.semantic_type} | {field.max_encoded_size} | {field.transform} |\n" for field in event.fields)
        docs += "\n"
    return {
        "android/tracebox-api/src/main/kotlin/dev/tracebox/api/generated/GeneratedSchema.kt": kotlin,
        "native/include/tracebox/generated_events.h": c,
        "rust/tracebox-sys/src/generated.rs": rust,
        "schema/generated/tracebox_records.proto": proto,
        "schema/generated/decoder-metadata.json": json.dumps(metadata, indent=2, sort_keys=True) + "\n",
        "schema/generated/disclosure-labels.json": json.dumps(labels, indent=2, sort_keys=True) + "\n",
        "docs/generated/schema-reference.md": docs,
    }

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--schema", type=pathlib.Path, default=ROOT / "schema" / "events.json")
    parser.add_argument("--out", type=pathlib.Path, default=ROOT)
    args = parser.parse_args()
    raw = args.schema.read_bytes()
    try:
        schema = parse_schema(json.loads(raw), raw.decode("utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError, SchemaError) as error:
        print(f"schema compilation failed: {error}", file=sys.stderr)
        return 1
    fingerprint = hashlib.sha256(raw).hexdigest()
    for relative, content in render(schema, fingerprint).items():
        target = args.out / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8", newline="\n")
    print(f"schema fingerprint {fingerprint}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
