"""Generate all Phase 1 schema consumers from one strict JSON model."""
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tooling" / "schema-model"))
from schema_model import SchemaError, parse_schema  # noqa: E402


def _kotlin_name(name: str) -> str:
    return name[:1].lower() + name[1:]


def _kotlin_camel_name(name: str) -> str:
    first, *rest = name.split("_")
    return first + "".join(part[:1].upper() + part[1:] for part in rest)


def _direct_boot_projection(schema) -> tuple[dict, str]:
    direct_boot_events = [event for event in schema.events if event.direct_boot_eligible]
    if len(direct_boot_events) != 1:
        raise SchemaError("Direct Boot v2 requires exactly one generated C0 event")
    event = direct_boot_events[0]
    projection = {
        "projection_version": 1,
        "event": {
            "id": event.id,
            "name": event.name,
            "category": event.category,
            "retention": event.retention,
            "package_visibility": event.package_visibility,
            "direct_boot_eligible": event.direct_boot_eligible,
            "category_mask": 1 << schema.events.index(event),
            "fields": [field.__dict__ for field in event.fields],
        },
    }
    canonical = json.dumps(
        projection,
        ensure_ascii=True,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")
    return projection, hashlib.sha256(canonical).hexdigest()


def render(schema, fingerprint: str) -> dict[str, str]:
    kotlin_types = {"u16": "UShort", "u32": "UInt", "u64": "ULong", "i32": "Int", "enum": "UInt", "fixed32": "UInt"}
    c_types = {"u16": "uint16_t", "u32": "uint32_t", "u64": "uint64_t", "i32": "int32_t", "enum": "uint32_t", "fixed32": "uint32_t"}
    rust_types = {"u16": "u16", "u32": "u32", "u64": "u64", "i32": "i32", "enum": "u32", "fixed32": "u32"}
    protobuf_types = {"u16": "uint32", "u32": "uint32", "u64": "uint64", "i32": "int32", "enum": "uint32", "fixed32": "fixed32"}
    metadata = {
        "schema_version": schema.version,
        "fingerprint": fingerprint,
        "events": [
            {
                "id": event.id, "name": event.name, "category": event.category,
                "retention": event.retention, "package_visibility": event.package_visibility,
                "direct_boot_eligible": event.direct_boot_eligible,
                "fields": [field.__dict__ for field in event.fields],
            } for event in schema.events
        ],
    }
    kotlin = """// Generated by tooling/schema-compiler/compile_schema.py. Do not edit.
package dev.tracebox.api.generated

import dev.tracebox.api.DiagnosticContext
import dev.tracebox.api.Diagnostics

enum class GeneratedEventId(val stableId: Int) {
""" + "".join(f"    {event.name.upper()}({event.id}),\n" for event in schema.events) + "}\n\n"
    kotlin += f"""object GeneratedSchemaFingerprint {{
    const val HEX: String = "{fingerprint}"

    fun bytes(): ByteArray = ByteArray(HEX.length / 2) {{ index ->
        HEX.substring(index * 2, index * 2 + 2).toInt(16).toByte()
    }}
}}

"""
    kotlin += """/** A schema-defined, bounded recording value. */
sealed interface GeneratedRecord {
    val eventId: GeneratedEventId
}

"""
    for event in schema.events:
        params = "\n".join(f"    val {_kotlin_name(field.name)}: {kotlin_types[field.semantic_type]}," for field in event.fields)
        kotlin += f"""/** Schema event {event.id}; fields are privacy-classified in the schema. */
class Generated{event.name}(
{params}
) : GeneratedRecord {{
    override val eventId = GeneratedEventId.{event.name.upper()}
}}

"""
    kotlin += "object GeneratedDiagnostics {\n"
    for event in schema.events:
        params = ", ".join(f"{_kotlin_name(field.name)}: {kotlin_types[field.semantic_type]}" for field in event.fields)
        args = ", ".join(_kotlin_name(field.name) for field in event.fields)
        kotlin += f"""    fun {_kotlin_name(event.name)}(diagnostics: Diagnostics, {params}, context: DiagnosticContext? = null) {{
        if (diagnostics.eventEnabled(GeneratedEventId.{event.name.upper()})) {{
            diagnostics.record(Generated{event.name}({args}), context)
        }}
    }}
"""
    kotlin += "}\n"
    kotlin += """
/** Generated export metadata; snapshot transformation must use this schema contract. */
object GeneratedExportMetadata {
    fun transforms(eventId: GeneratedEventId): List<String> = when (eventId) {
"""
    for event in schema.events:
        transforms = ", ".join(f'"{field.transform}"' for field in event.fields)
        kotlin += f"        GeneratedEventId.{event.name.upper()} -> listOf({transforms})\n"
    kotlin += """    }

    fun standardVisible(eventId: GeneratedEventId): Boolean = when (eventId) {
"""
    for event in schema.events:
        kotlin += f"        GeneratedEventId.{event.name.upper()} -> {str(event.package_visibility == 'standard').lower()}\n"
    kotlin += """    }
}
"""
    direct_boot_events = [event for event in schema.events if event.direct_boot_eligible]
    _, direct_boot_fingerprint = _direct_boot_projection(schema)
    direct_boot_event = direct_boot_events[0]
    direct_boot = """// Generated by tooling/schema-compiler/compile_schema.py. Do not edit.
package dev.tracebox.directboot

""" + "".join(
        f"import dev.tracebox.api.generated.Generated{event.name}\n"
        for event in direct_boot_events
) + """
/** Fingerprint of only the canonical Direct Boot-eligible projection and its policy category. */
object GeneratedDirectBootSchemaFingerprint {
    const val HEX: String = "%s"

    fun bytes(): ByteArray = ByteArray(HEX.length / 2) { index ->
        HEX.substring(index * 2, index * 2 + 2).toInt(16).toByte()
    }
}

/** Generated C0-only Direct Boot projection. No arbitrary payload or privacy override exists. */
internal data class C0DirectBootRecord(
    val schemaFingerprint: ByteArray,
""" % direct_boot_fingerprint
    direct_boot += "".join(
        f"    val {_kotlin_camel_name(field.name)}: {kotlin_types[field.semantic_type]},\n"
        for field in direct_boot_event.fields
    )
    direct_boot += """    val elapsedMillis: Long,
    val readinessCode: Int,
    val categoryMask: Long,
) {
    init {
        require(schemaFingerprint.size == 32)
"""
    if "policy_epoch" in {field.name for field in direct_boot_event.fields}:
        direct_boot += "        require(policyEpoch <= Long.MAX_VALUE.toULong())\n"
    direct_boot += """        require(elapsedMillis >= 0)
        require(readinessCode in 0..255)
        require(categoryMask in GENERATED_DIRECT_BOOT_CATEGORIES)
    }
}

/** Schema-generated wrapper admitting only events whose complete schema is C0. */
class GeneratedDirectBootRecord private constructor(
    internal val c0: C0DirectBootRecord,
) {
    companion object {
"""
    for event in direct_boot_events:
        factory_name = event.name.removesuffix("Record")
        category = 1 << schema.events.index(event)
        direct_boot += f"""        fun from{factory_name}(
            schemaFingerprint: ByteArray,
            value: Generated{event.name},
            elapsedMillis: Long,
            readinessCode: Int,
        ): GeneratedDirectBootRecord {{
            return GeneratedDirectBootRecord(
                C0DirectBootRecord(
                    schemaFingerprint.copyOf(),
"""
        direct_boot += "".join(
            f"                    value.{field.name},\n"
            for field in event.fields
        )
        direct_boot += f"""                    elapsedMillis,
                    readinessCode,
                    {category}L,
                ),
            )
        }}

        @Deprecated(
            message = "The category is generated and cannot be overridden",
            replaceWith = ReplaceWith("from{factory_name}(schemaFingerprint, value, elapsedMillis, readinessCode)"),
        )
        fun from{factory_name}(
            schemaFingerprint: ByteArray,
            value: Generated{event.name},
            elapsedMillis: Long,
            readinessCode: Int,
            categoryMask: Long,
        ): GeneratedDirectBootRecord {{
            require(categoryMask == {category}L)
            return from{factory_name}(schemaFingerprint, value, elapsedMillis, readinessCode)
        }}

"""
    direct_boot += """    }
}

internal val GENERATED_DIRECT_BOOT_CATEGORIES = setOf(
"""
    direct_boot += "".join(
        f"    {1 << schema.events.index(event)}L,\n"
        for event in direct_boot_events
    )
    direct_boot += ")\n"
    c = """/* Generated by tooling/schema-compiler/compile_schema.py. Do not edit. */
#ifndef TRACEBOX_GENERATED_EVENTS_H_
#define TRACEBOX_GENERATED_EVENTS_H_
#include <stdint.h>
/* Requires tb_header_v1 and tb_status_v1 from tracebox/abi.h, which are
 * defined before this header is included there. Do not include this
 * header directly; include tracebox/abi.h instead. */
#ifdef __cplusplus
extern "C" {
#endif
typedef enum {
""" + "".join(f"  TB_EVENT_{event.name.upper()} = {event.id},\n" for event in schema.events) + "} tb_event_id_v1;\n\n"
    for event in schema.events:
        c += f"typedef struct {{\n  tb_header_v1 header;\n"
        c += "".join(f"  {c_types[field.semantic_type]} {field.name}; /* {field.privacy}, max encoded {field.max_encoded_size} */\n" for field in event.fields)
        c += f"}} tb_generated_{event.name.lower()}_v1;\n"
        c += f"tb_status_v1 tb_record_generated_{event.name.lower()}_v1(const tb_generated_{event.name.lower()}_v1* value, uint32_t recorder_ready);\n\n"
    c += "#ifdef __cplusplus\n}\n#endif\n\n#endif\n"
    c_source = """/* Generated by tooling/schema-compiler/compile_schema.py. Do not edit. */
#include "tracebox/abi.h"

#include <stddef.h>

"""
    for event in schema.events:
        type_name = f"tb_generated_{event.name.lower()}_v1"
        function_name = f"tb_record_generated_{event.name.lower()}_v1"
        first_field = event.fields[0].name
        c_source += f"""tb_status_v1 {function_name}(const {type_name}* value,
                                              uint32_t recorder_ready) {{
  tb_status_v1 status = tb_validate_header_v1(
      value == NULL ? NULL : &value->header,
      (uint32_t)offsetof({type_name}, {first_field}),
      (uint32_t)sizeof({type_name}));
  if (status != TB_STATUS_OK) {{
    return status;
  }}
  if (recorder_ready == 0u) {{
    return TB_STATUS_NOT_READY;
  }}
  return TB_STATUS_OK;
}}

"""
    rust = (
        "// Generated by tooling/schema-compiler/compile_schema.py. Do not edit.\n"
        + "pub const SCHEMA_FINGERPRINT: &str =\n    \"" + fingerprint + "\";\n"
        + "#[repr(u32)]\n#[derive(Clone, Copy, Debug, PartialEq, Eq)]\npub enum EventId {\n"
        + "".join(f"    {event.name} = {event.id},\n" for event in schema.events)
        + "}\n\n"
    )
    for event in schema.events:
        rust += f"/// Schema-defined C ABI input for event {event.id}.\n#[repr(C)]\n#[derive(Clone, Copy, Debug, PartialEq, Eq)]\npub struct {event.name}V1 {{\n    /// Required ABI header.\n    pub header: crate::HeaderV1,\n"
        rust += "".join(f"    /// {field.privacy}; maximum encoded size {field.max_encoded_size}.\n    pub {field.name}: {rust_types[field.semantic_type]},\n" for field in event.fields)
        rust += "}\n\n"
    rust = rust.rstrip() + "\n"
    proto = "// Generated protobuf-compatible definitions. No free-form values.\nsyntax = \"proto3\";\npackage tracebox.generated;\n" + "".join(
        "message " + event.name + " {\n" + "".join(
            f"  {protobuf_types[field.semantic_type]} {field.name} = {field.id}; // max encoded size {field.max_encoded_size}; privacy {field.privacy}\n" for field in event.fields
        ) + "}\n" for event in schema.events
    )
    labels = {
        event.name: f"{event.category}: includes only " +
        ", ".join(f"{field.privacy} {field.name}" for field in event.fields)
        for event in schema.events
    }
    docs = "# Generated Tracebox schema reference\n\n"
    for event in schema.events:
        docs += f"## {event.name} (`{event.id}`)\n\n"
        docs += f"Category: `{event.category}`; retention: `{event.retention}`; package: `{event.package_visibility}`; Direct Boot: `{event.direct_boot_eligible}`.\n\n"
        docs += "| Field ID | Field | Privacy | Type | Maximum encoded size | Transformation |\n|---:|---|---|---|---:|---|\n"
        docs += "".join(f"| {field.id} | {field.name} | {field.privacy} | {field.semantic_type} | {field.max_encoded_size} | {field.transform} |\n" for field in event.fields)
        docs += "\n"
    return {
        "android/tracebox-api/src/main/kotlin/dev/tracebox/api/generated/GeneratedSchema.kt": kotlin,
        "android/tracebox-directboot/src/main/kotlin/dev/tracebox/directboot/GeneratedDirectBootSchema.kt": direct_boot,
        "native/include/tracebox/generated_events.h": c,
        "native/generated/tracebox_generated_events.c": c_source,
        "rust/tracebox-sys/src/generated.rs": rust,
        "schema/generated/tracebox_records.proto": proto,
        "schema/generated/decoder-metadata.json": json.dumps(metadata, indent=2, sort_keys=True) + "\n",
        "schema/generated/disclosure-labels.json": json.dumps(labels, indent=2, sort_keys=True) + "\n",
        "docs/generated/schema-reference.md": docs,
    }

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--schema", type=pathlib.Path, default=ROOT / "schema" / "events.json")
    parser.add_argument("--out", type=pathlib.Path, default=ROOT)
    args = parser.parse_args()
    raw = args.schema.read_bytes()
    try:
        schema = parse_schema(json.loads(raw), raw.decode("utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError, SchemaError) as error:
        print(f"schema compilation failed: {error}", file=sys.stderr)
        return 1
    fingerprint = hashlib.sha256(raw).hexdigest()
    for relative, content in render(schema, fingerprint).items():
        target = args.out / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8", newline="\n")
    print(f"schema fingerprint {fingerprint}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
