// Generated by tooling/schema-compiler/compile_schema.py. Do not edit.
pub const SCHEMA_FINGERPRINT: &str = "6cab7df4c1845824d3db406e5c4702727585556758764a05d43014c66dcfa92c";
#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum EventId {
    StructuralSummary = 1,
    EmergencyRecord = 2,
    Breadcrumb = 3,
    HandledError = 4,
}
