// Generated by tooling/schema-compiler/compile_schema.py. Do not edit.
use super::{PayloadReader, RecordDecodeError, json_string};

#[rustfmt::skip]
pub(crate) const SCHEMA_FINGERPRINT: [u8; 32] = [
    0xe0, 0x72, 0xb1, 0x84, 0x63, 0x7c, 0xe3, 0x02,
    0xf6, 0x8f, 0x55, 0x5e, 0x81, 0x8d, 0x94, 0xe4,
    0x97, 0xcc, 0xbd, 0x0a, 0xcb, 0xa7, 0xcc, 0x1e,
    0xf1, 0x31, 0x53, 0x1b, 0x8f, 0x4c, 0x8f, 0x10,
];
#[rustfmt::skip]
pub(crate) const EVENTS: &[(u32, &str)] = &[
    (1, "StructuralSummary"),
    (2, "EmergencyRecord"),
    (3, "Breadcrumb"),
    (4, "HandledError"),
    (5, "ManagedCrash"),
    (6, "RustPanic"),
    (7, "AnrCandidate"),
    (8, "OsExit"),
    (9, "LogRecord"),
    (10, "ExceptionRecord"),
    (11, "AnrTrace"),
];

#[rustfmt::skip]
pub(crate) fn event_type_name(event_id: u32) -> Option<&'static str> {
    EVENTS.iter().find_map(|(id, name)| (*id == event_id).then_some(*name))
}

#[rustfmt::skip]
pub(crate) fn event_id_for_selector(selector: &str) -> Option<u32> {
    selector
        .parse::<u32>()
        .ok()
        .filter(|event_id| event_type_name(*event_id).is_some())
        .or_else(|| {
            EVENTS
                .iter()
                .find_map(|(id, name)| name.eq_ignore_ascii_case(selector).then_some(*id))
        })
}

#[rustfmt::skip]
pub(crate) fn decode_generated_payload(
    event_id: u32,
    payload: &[u8],
) -> Result<Vec<(String, String)>, RecordDecodeError> {
    let mut reader = PayloadReader::new(event_id, payload);
    let fields = match event_id {
        1 => vec![
            ("stream_count".into(), reader.read_u32()?.to_string()),
            ("thread_count".into(), reader.read_u32()?.to_string()),
            ("module_count".into(), reader.read_u32()?.to_string()),
            ("exception_code".into(), reader.read_u32()?.to_string()),
            ("processor_architecture".into(), reader.read_u16()?.to_string()),
        ],
        2 => vec![
            ("slot_sequence".into(), reader.read_u64()?.to_string()),
            ("policy_epoch".into(), reader.read_u64()?.to_string()),
            ("signal_number".into(), reader.read_i32()?.to_string()),
            ("signal_code".into(), reader.read_i32()?.to_string()),
            ("process_role".into(), reader.read_u32()?.to_string()),
            ("thread_role".into(), reader.read_u32()?.to_string()),
            ("flags".into(), reader.read_u64()?.to_string()),
        ],
        3 => vec![
            ("code".into(), reader.read_u32()?.to_string()),
            ("monotonic_time_ns".into(), reader.read_u64()?.to_string()),
        ],
        4 => vec![
            ("kind".into(), reader.read_u32()?.to_string()),
            ("frame_count".into(), reader.read_u16()?.to_string()),
        ],
        5 => vec![
            ("primary_exception_code".into(), reader.read_u32()?.to_string()),
            ("cause_count".into(), reader.read_u16()?.to_string()),
            ("frame_count".into(), reader.read_u16()?.to_string()),
            ("flags".into(), reader.read_u32()?.to_string()),
        ],
        6 => vec![
            ("payload_class".into(), reader.read_u32()?.to_string()),
            ("thread_role".into(), reader.read_u32()?.to_string()),
            ("location_code".into(), reader.read_u32()?.to_string()),
            ("flags".into(), reader.read_u32()?.to_string()),
        ],
        7 => vec![
            ("elapsed_millis".into(), reader.read_u32()?.to_string()),
            ("sample_count".into(), reader.read_u16()?.to_string()),
            ("frame_count".into(), reader.read_u16()?.to_string()),
            ("nonfatal_result".into(), reader.read_u32()?.to_string()),
            ("flags".into(), reader.read_u32()?.to_string()),
        ],
        8 => vec![
            ("reason".into(), reader.read_i32()?.to_string()),
            ("status".into(), reader.read_i32()?.to_string()),
            ("importance".into(), reader.read_i32()?.to_string()),
            ("link_confidence".into(), reader.read_u32()?.to_string()),
            ("artifact_state".into(), reader.read_u32()?.to_string()),
        ],
        9 => vec![
            ("level".into(), reader.read_u32()?.to_string()),
            ("category".into(), reader.read_u32()?.to_string()),
            ("template_fingerprint".into(), reader.read_u64()?.to_string()),
            ("rendered_message".into(), json_string(reader.read_utf8(1024)?)),
            ("privacy_flags".into(), reader.read_u32()?.to_string()),
            ("monotonic_time_ns".into(), reader.read_u64()?.to_string()),
            ("duration_ns".into(), reader.read_u64()?.to_string()),
            ("outcome".into(), reader.read_u32()?.to_string()),
        ],
        10 => vec![
            ("kind".into(), reader.read_u32()?.to_string()),
            ("exception_type".into(), json_string(reader.read_utf8(256)?)),
            ("frame_count".into(), reader.read_u16()?.to_string()),
            ("stack_fingerprint".into(), reader.read_u64()?.to_string()),
            ("stack_trace".into(), json_string(reader.read_utf8(2048)?)),
            ("monotonic_time_ns".into(), reader.read_u64()?.to_string()),
        ],
        11 => vec![
            ("elapsed_millis".into(), reader.read_u32()?.to_string()),
            ("frame_count".into(), reader.read_u16()?.to_string()),
            ("stack_fingerprint".into(), reader.read_u64()?.to_string()),
            ("stack_trace".into(), json_string(reader.read_utf8(2048)?)),
        ],
        _ => return Err(RecordDecodeError::UnknownEventType(event_id)),
    };
    reader.finish()?;
    Ok(fields)
}
