// Generated by tooling/schema-compiler/compile_schema.py. Do not edit.
pub const SCHEMA_FINGERPRINT: &str =
    "e072b184637ce302f68f555e818d94e497ccbd0acba7cc1ef131531b8f4c8f10";
#[repr(u32)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum EventId {
    StructuralSummary = 1,
    EmergencyRecord = 2,
    Breadcrumb = 3,
    HandledError = 4,
    ManagedCrash = 5,
    RustPanic = 6,
    AnrCandidate = 7,
    OsExit = 8,
    LogRecord = 9,
    ExceptionRecord = 10,
    AnrTrace = 11,
}

/// Schema-defined C ABI input for event 1.
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct StructuralSummaryV1 {
    /// Required ABI header.
    pub header: crate::HeaderV1,
    /// C0; maximum encoded size 5.
    pub stream_count: u32,
    /// C0; maximum encoded size 5.
    pub thread_count: u32,
    /// C0; maximum encoded size 5.
    pub module_count: u32,
    /// C0; maximum encoded size 5.
    pub exception_code: u32,
    /// C0; maximum encoded size 3.
    pub processor_architecture: u16,
}

/// Schema-defined C ABI input for event 2.
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct EmergencyRecordV1 {
    /// Required ABI header.
    pub header: crate::HeaderV1,
    /// C0; maximum encoded size 10.
    pub slot_sequence: u64,
    /// C0; maximum encoded size 10.
    pub policy_epoch: u64,
    /// C0; maximum encoded size 5.
    pub signal_number: i32,
    /// C0; maximum encoded size 5.
    pub signal_code: i32,
    /// C0; maximum encoded size 5.
    pub process_role: u32,
    /// C0; maximum encoded size 5.
    pub thread_role: u32,
    /// C0; maximum encoded size 10.
    pub flags: u64,
}

/// Schema-defined C ABI input for event 3.
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct BreadcrumbV1 {
    /// Required ABI header.
    pub header: crate::HeaderV1,
    /// C1; maximum encoded size 5.
    pub code: u32,
    /// C1; maximum encoded size 10.
    pub monotonic_time_ns: u64,
}

/// Schema-defined C ABI input for event 4.
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct HandledErrorV1 {
    /// Required ABI header.
    pub header: crate::HeaderV1,
    /// C1; maximum encoded size 5.
    pub kind: u32,
    /// C1; maximum encoded size 3.
    pub frame_count: u16,
}

/// Schema-defined C ABI input for event 5.
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ManagedCrashV1 {
    /// Required ABI header.
    pub header: crate::HeaderV1,
    /// C1; maximum encoded size 5.
    pub primary_exception_code: u32,
    /// C0; maximum encoded size 3.
    pub cause_count: u16,
    /// C0; maximum encoded size 3.
    pub frame_count: u16,
    /// C0; maximum encoded size 5.
    pub flags: u32,
}

/// Schema-defined C ABI input for event 6.
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RustPanicV1 {
    /// Required ABI header.
    pub header: crate::HeaderV1,
    /// C0; maximum encoded size 5.
    pub payload_class: u32,
    /// C0; maximum encoded size 5.
    pub thread_role: u32,
    /// C1; maximum encoded size 5.
    pub location_code: u32,
    /// C0; maximum encoded size 5.
    pub flags: u32,
}

/// Schema-defined C ABI input for event 7.
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct AnrCandidateV1 {
    /// Required ABI header.
    pub header: crate::HeaderV1,
    /// C0; maximum encoded size 5.
    pub elapsed_millis: u32,
    /// C0; maximum encoded size 3.
    pub sample_count: u16,
    /// C0; maximum encoded size 3.
    pub frame_count: u16,
    /// C0; maximum encoded size 5.
    pub nonfatal_result: u32,
    /// C0; maximum encoded size 5.
    pub flags: u32,
}

/// Schema-defined C ABI input for event 8.
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct OsExitV1 {
    /// Required ABI header.
    pub header: crate::HeaderV1,
    /// C0; maximum encoded size 5.
    pub reason: i32,
    /// C0; maximum encoded size 5.
    pub status: i32,
    /// C0; maximum encoded size 5.
    pub importance: i32,
    /// C0; maximum encoded size 5.
    pub link_confidence: u32,
    /// C0; maximum encoded size 5.
    pub artifact_state: u32,
}

/// Schema-defined C ABI input for event 9.
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct LogRecordV1 {
    /// Required ABI header.
    pub header: crate::HeaderV1,
    /// C0; maximum encoded size 5.
    pub level: u32,
    /// C0; maximum encoded size 5.
    pub category: u32,
    /// C1; maximum encoded size 10.
    pub template_fingerprint: u64,
    /// C2; maximum encoded size 1026.
    pub rendered_message: crate::Utf8ViewV1,
    /// C0; maximum encoded size 5.
    pub privacy_flags: u32,
    /// C1; maximum encoded size 10.
    pub monotonic_time_ns: u64,
    /// C0; maximum encoded size 10.
    pub duration_ns: u64,
    /// C0; maximum encoded size 5.
    pub outcome: u32,
}

/// Schema-defined C ABI input for event 10.
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ExceptionRecordV1 {
    /// Required ABI header.
    pub header: crate::HeaderV1,
    /// C0; maximum encoded size 5.
    pub kind: u32,
    /// C1; maximum encoded size 258.
    pub exception_type: crate::Utf8ViewV1,
    /// C0; maximum encoded size 3.
    pub frame_count: u16,
    /// C1; maximum encoded size 10.
    pub stack_fingerprint: u64,
    /// C1; maximum encoded size 2050.
    pub stack_trace: crate::Utf8ViewV1,
    /// C1; maximum encoded size 10.
    pub monotonic_time_ns: u64,
}

/// Schema-defined C ABI input for event 11.
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct AnrTraceV1 {
    /// Required ABI header.
    pub header: crate::HeaderV1,
    /// C0; maximum encoded size 5.
    pub elapsed_millis: u32,
    /// C0; maximum encoded size 3.
    pub frame_count: u16,
    /// C1; maximum encoded size 10.
    pub stack_fingerprint: u64,
    /// C1; maximum encoded size 2050.
    pub stack_trace: crate::Utf8ViewV1,
}
